3 commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,7 +32,7 @@ jobs:
             if [ -d .git ]; then
               git pull --ff-only || { echo "git pull failed"; exit 1; }
             else
-              git clone https://github.com/vardhanreddy2003/poc1.git . || { echo "git clone failed"; exit 1; }
+              git clone https://github.com/FReddy116/poc1.git . || { echo "git clone failed"; exit 1; }
             fi
 
             # nginx handling
